# docker-compose.yml
version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - redis

  redis:
    image: redis
    volumes:
      - redis-data:/data

volumes:
  redis-data:


