apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-app.fullname" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
data:
  dbname: {{ .Values.config.dbname }}
  dbhost: {{ .Values.config.dbhost }}
