# docker-compose.yml
version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    container_name: simple-web-app
    image: nginx-web-apps
    ports:
      - "8080:80"
    depends_on:
      - redis

  redis:
    image: redis


